begin;

alter table public.services
  add column if not exists display_order integer;

update public.services set price_min_cents = null, price_max_cents = null;

with service_updates(id, name, name_en, description, description_en, service_group, service_group_en, display_order) as (
  values
    ('f260a358-7b93-4671-9cba-8ab8c2d558d1', 'Depilacija bikini zone', 'Bikini Line Waxing', 'Uklanjanje dlačica uz rub bikini zone za uredan izgled.', 'Hair removal along the bikini line for a clean, neat finish.', 'Depilacija', 'Waxing', 6),
    ('f3bf0f68-7c62-4db5-97e7-2eb7d18aad9c', 'Proširena bikini depilacija', 'Bikini Strip', 'Depilacija proširenog bikini područja uz prirodan izgled.', 'Extended bikini waxing while maintaining a natural look.', 'Depilacija', 'Waxing', 23),
    ('46bb4995-3445-40a5-b39e-ffe4fbef88ac', 'Brazilska depilacija', 'Brazilian waxing', 'Brazilska depilacija za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Brazilian waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 2),
    ('05723404-ae30-4b1a-a3f4-b98df3e1e800', 'Depilacija brade', 'Chin', 'Precizno uklanjanje neželjenih dlačica s područja brade.', 'Precise chin waxing for smooth skin.', 'Depilacija', 'Waxing', 3),
    ('44138b19-f280-4fb1-be5a-fc2026a7fbe1', 'Cijele noge + bikini', 'Full legs + bikini line', 'Cijele noge + bikini za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Full legs + bikini line for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 1),
    ('77d75918-7843-4f27-ab7d-5c17f5c9d922', 'Cijele noge + brazilska', 'Full legs + Brazilian', 'Cijele noge + brazilska za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Full legs + Brazilian for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 2),
    ('6af47b51-a072-413f-b137-28f72a88616b', 'Depilacija bikini zone', 'Bikini line waxing', 'Depilacija bikini zone za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Bikini line waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 6),
    ('556d2cbf-7665-48f5-a7c1-5efd0446c4d7', 'Depilacija leđa / prsa', 'Back / chest waxing', 'Depilacija leđa / prsa za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Back / chest waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 9),
    ('63c42149-9915-4bf1-9369-3079a771415e', 'Depilacija lica', 'Face waxing', 'Depilacija lica za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Face waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 11),
    ('6e7f5f91-d8e6-4363-a047-f3fb0692c454', 'Depilacija nadusnica', 'Upper lip waxing', 'Depilacija nadusnica za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Upper lip waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 13),
    ('01621f05-d983-4a6e-b33b-83a8ede75960', 'Depilacija pazuha', 'Underarm waxing', 'Depilacija pazuha za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Underarm waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 14),
    ('0be93a53-f5e2-4e8a-9c42-2ded335a1e8e', 'Depilacija ruku', 'Arm waxing', 'Depilacija ruku za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Arm waxing for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 15),
    ('d40ed724-6999-4682-9374-c770b8267394', 'Depilacija cijelih ruku', 'Full Arms', 'Potpuna depilacija ruku za dugotrajan osjećaj glatkoće.', 'Full arm waxing for soft, smooth skin.', 'Depilacija', 'Waxing', 4),
    ('a7812346-b70b-4da8-a158-33db96c82b1b', 'Depilacija cijelog lica', 'Full Face Waxing', 'Depilacija cijelog lica za glatku i njegovanu kožu.', 'Full facial waxing for smooth, refreshed skin.', 'Depilacija', 'Waxing', 5),
    ('7e42e872-9a1f-4cc3-a23f-53d36daa4438', 'Depilacija cijelih nogu', 'Full Legs', 'Potpuna depilacija nogu za savršeno glatku kožu.', 'Full leg waxing for silky smooth skin.', 'Depilacija', 'Waxing', 4),
    ('4525038d-0ae1-4b83-bc98-6b6e47b605e8', 'Cijele noge + bikini zona', 'Full legs + Bikini Line', 'Cijele noge + bikini zona za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Full legs + Bikini Line for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 1),
    ('adbc608a-0df0-4e39-bcc8-362aa500f15d', 'Cijele noge + brazilska depilacija', 'Full Legs + Brazilian', 'Cijele noge + brazilska depilacija za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Full Legs + Brazilian for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 3),
    ('f8b48881-3e43-4010-9199-ea0d028560ce', 'Hollywood depilacija (potpuna brazilska)', 'Hollywood (Full Brazilian)', 'Potpuno uklanjanje dlačica intimnog područja.', 'Complete intimate waxing for perfectly smooth skin.', 'Depilacija', 'Waxing', 17),
    ('772f4bcd-6b42-4c9a-9fcf-3edc1daf7f96', 'Depilacija podlaktica', 'Lower Arms', 'Depilacija podlaktica za uredan i njegovan izgled.', 'Lower arm waxing for smooth, well-groomed skin.', 'Depilacija', 'Waxing', 16),
    ('3b28d672-a67b-4614-b55f-ab0a2e1805cc', 'Depilacija potkoljenica', 'Lower Legs', 'Depilacija potkoljenica za dugotrajno glatku kožu.', 'Lower leg waxing for long-lasting smoothness.', 'Depilacija', 'Waxing', 17),
    ('b4cfb2f4-565b-458f-a42e-e9391a6b54ad', 'Potkoljenice / natkoljenica', 'Lower legs / upper legs', 'Potkoljenice / natkoljenica za glatku i urednu kožu uz profesionalnu tehniku prilagođenu osjetljivosti tretiranog područja.', 'Lower legs / upper legs for smooth, well-groomed skin using a professional technique adapted to the treated area.', 'Depilacija', 'Waxing', 22),
    ('7dc7e0b8-3857-451a-af00-69067d18a5c4', 'Depilacija pazuha', 'Underarms', 'Učinkovita depilacija područja pazuha za dugotrajan osjećaj svježine.', 'Gentle underarm waxing for smooth, long-lasting results.', 'Depilacija', 'Waxing', 14),
    ('a4122728-1f54-44ec-bf6b-e55d1facfd06', 'Depilacija nadusnice', 'Upper Lip', 'Brza i nježna depilacija gornje usne.', 'Quick and gentle upper lip waxing.', 'Depilacija', 'Waxing', 13),
    ('d5604514-e9dc-4dfd-b65e-6125c6b52927', 'Konzultacije', 'Consultation', 'Konzultacije omogućuje stručnu procjenu potreba i preporuku odgovarajućeg tretmana.', 'Consultation provides a professional assessment of your needs and a recommendation for the most suitable treatment.', 'Konzultacije', 'Consultation', 1),
    ('5235bbc5-926a-4a1d-86c2-34b73682f878', 'Brada', 'Chin', 'Brada – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Chin – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 1),
    ('c2c05a24-e3b3-4ded-8caf-7ea15b989abb', 'Brazilska', 'Brazilian', 'Brazilska – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Brazilian – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 2),
    ('01a77dc9-5e6a-4994-a51f-30285408330e', 'Cijele noge', 'Full legs', 'Cijele noge – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Full legs – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 3),
    ('6df25301-dc89-4e38-8b3f-8eb45ec771a5', 'Cijelo lice', 'Full face', 'Cijelo lice – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Full face – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 4),
    ('99cfac81-43f1-4c03-b36d-f8684215a47c', 'Leđa + prsa + trbuh', 'Back + chest + abdomen', 'Leđa + prsa + trbuh – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Back + chest + abdomen – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 5),
    ('c6f82117-42d7-4681-be27-b3b1bdf6ccba', 'Muška leđa', 'Men’s back', 'Muška leđa – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Men’s back – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 6),
    ('dff87afc-2169-4087-861f-69dd2d7e81b5', 'Nadusnice', 'Upper lip', 'Nadusnice – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Upper lip – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 7),
    ('8661e43c-63d6-4996-99fe-a791f57859c5', 'Pazusi', 'Underarms', 'Pazusi – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Underarms – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 8),
    ('af26e2d4-a342-4a02-ac79-a8b00cf15540', 'Prsa', 'Chest', 'Prsa – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Chest – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 9),
    ('1039e65e-998c-4c10-b4ae-01511f62b03a', 'Prsa + trbuh', 'Chest + abdomen', 'Prsa + trbuh – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Chest + abdomen – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 10),
    ('31a71182-c1eb-4487-85bd-27efd657f88f', 'Ruke', 'Arms', 'Ruke – tretman laserske epilacije za dugotrajnije smanjenje neželjenih dlačica na odabranom području.', 'Arms – laser hair removal treatment designed for longer-lasting reduction of unwanted hair in the selected area.', 'Laserska epilacija', 'Laser Hair Removal', 11),
    ('2d176565-218c-4af5-9e8b-48666cd23b81', 'Anti-age tretman', 'Anti-Ageing Treatment', 'Tretman usmjeren na smanjenje znakova starenja i poboljšanje tonusa kože.', 'A rejuvenating facial designed to reduce visible signs of ageing and improve skin firmness.', 'Njega lica', 'Facial Treatments', 1),
    ('a66d100a-3fdd-4dc7-8d5a-b4f5c84e5aa0', 'Body & Soul Signature Lift & Sculpt Ritual', 'Body & Soul Signature Lift & Sculpt Ritual', 'Body & Soul Signature Lift & Sculpt Ritual je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Body & Soul Signature Lift & Sculpt Ritual is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 2),
    ('fa1821cb-7e5b-4e1a-ad8c-8e302baf5115', 'Body & Soul Signature Ritual', 'Body & Soul Signature Ritual', 'Body & Soul Signature Ritual je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Body & Soul Signature Ritual is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 3),
    ('67098bcf-a8c6-4aa4-9436-a20855bedd86', 'Tretman za blistavost i sjaj', 'Brightening & Glow Treatment', 'Tretman za blistaviji ten, ujednačeniji ton kože i prirodan sjaj.', 'A facial that enhances radiance, evens skin tone and restores a healthy glow.', 'Njega lica', 'Facial Treatments', 15),
    ('2b3d973f-42b6-49fa-b838-d5f5a870e63f', 'Circadia Rosacea Recovery Ritual', 'Circadia Rosacea Recovery Ritual', 'Circadia Rosacea Recovery Ritual je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Circadia Rosacea Recovery Ritual is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 4),
    ('06361a21-6d69-4d36-a931-2d28a0716e82', 'Čišćenje i hidratacija kože', 'Deep Cleansing Facial', 'Čišćenje i hidratacija kože je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Deep Cleansing Facial is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 16),
    ('f7e81746-6383-475e-ac07-f2825900c16c', 'Klasično čišćenje lica', 'Classic Facial Cleansing', 'Dubinsko čišćenje lica za zdraviju, svježiju i čistiju kožu.', 'A deep facial cleansing treatment for healthier, fresher and clearer skin.', 'Njega lica', 'Facial Treatments', 10),
    ('0db9067f-86e1-42f3-9074-72e774309f14', 'Collagen Boost – Dermapen 4', 'Collagen Boost – Dermapen 4', 'Collagen Boost – Dermapen 4 je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Collagen Boost – Dermapen 4 is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 5),
    ('7222a670-e4bc-41e5-aaa7-18b59e99aeef', 'Dubinska hidratacija lica', 'Deep Hydration Facial', 'Intenzivna hidratacija koja vraća koži svježinu, mekoću i elastičnost.', 'An intensive hydrating facial that restores softness, freshness and elasticity.', 'Njega lica', 'Facial Treatments', 7),
    ('1e831db8-aeb4-43a3-bf6f-99a364ef9a5e', 'Detox Purity Facial – Dermapen', 'Detox Purity Facial – Dermapen', 'Detox Purity Facial – Dermapen je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Detox Purity Facial – Dermapen is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 6),
    ('fc337731-7432-4227-9296-7009dc2fdd07', 'Firm & Lift – HIFU (lice i dekolte)', 'Firm & Lift – HIFU (face and décolleté)', 'Firm & Lift – HIFU (lice i dekolte) je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Firm & Lift – HIFU (face and décolleté) is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 8),
    ('86f2146b-cd83-4f2b-9ac3-9df77b95b284', 'Glass Skin Infusion - Mezoterapija Toskani', 'Glass Skin Infusion – Toskani Mesotherapy', 'Glass Skin Infusion - Mezoterapija Toskani je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Glass Skin Infusion – Toskani Mesotherapy is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 9),
    ('3fbcadaa-5d8e-426e-a346-a623a322cccc', 'Instant Glow Ritual', 'Calming Glow Ritual', 'Instant Glow Ritual je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Calming Glow Ritual is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 11),
    ('d1f7a56e-01ca-4201-a3aa-d7a5842674ad', 'Luxury Anti-Age Ritual', 'Luxury Anti-Age Ritual', 'Luxury Anti-Age Ritual je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Luxury Anti-Age Ritual is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 12),
    ('b8ff7ea3-dc2e-41ae-9e24-ce76e77a624f', 'Mummy & Baby Relax Ritual – masaža za trudnice', 'Mummy & Baby Relax Ritual – pregnancy massage', 'Mummy & Baby Relax Ritual – masaža za trudnice je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Mummy & Baby Relax Ritual – pregnancy massage is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 13),
    ('68290eb3-41df-46b4-af9f-401cec79ac11', 'Oxy tretman sa kisikom', 'Oxygen Facial Treatment', 'Oxy tretman sa kisikom je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Oxygen Facial Treatment is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 14),
    ('53b97f93-d265-435e-94ce-ac3f87a9c889', 'Radiance Peel – Circadia', 'Radiance Peel – Circadia', 'Radiance Peel – Circadia je profesionalni tretman lica prilagođen potrebama kože, s ciljem poboljšanja izgleda, svježine i osjećaja njege.', 'Radiance Peel – Circadia is a professional facial treatment tailored to the skin’s needs to improve its appearance, freshness and overall feeling of care.', 'Njega lica', 'Facial Treatments', 16),
    ('31c5fdc6-d055-4a75-bd54-6b3b39c7c4ac', 'Opuštajuća masaža lica', 'Relaxing Face Massage', 'Opuštajuća masaža lica koja potiče cirkulaciju i smanjuje napetost.', 'A relaxing facial massage that improves circulation and relieves tension.', 'Njega lica', 'Facial Treatments', 17),
    ('4919576e-2785-44f0-bf63-920653848376', 'Klasična manikura', 'Classic Manicure', 'Njega noktiju i ruku za uredan i njegovan izgled.', 'Nail and hand care for a clean, polished appearance.', 'Manikura', 'Manicure', 1),
    ('4b5bc4a4-b6d5-4b1c-98e6-7495d12e2066', 'Gel ekstenzije', 'Gel Extensions', 'Produživanje i oblikovanje noktiju profesionalnom gel tehnikom. Završna cijena ovisi o odabranoj dužini noktiju.', 'Professional gel nail extensions and shaping. The final price depends on the selected nail length.', 'Manikura', 'Manicure', 4),
    ('6dfb8b44-f58a-4c01-a612-ad55d8ece877', 'Uklanjanje trajnog laka', 'Gel Polish Removal', 'Sigurno i nježno uklanjanje gel laka bez oštećenja prirodnog nokta.', 'Safe removal of gel polish while protecting the natural nail.', 'Manikura', 'Manicure', 8),
    ('6f1078a8-5d7d-4d6c-b94c-3c2a126051a0', 'Manikura + trajni lak', 'Manicure + Gel Polish', 'Klasična manikura uz dugotrajni gel lak visokog sjaja.', 'Classic manicure finished with long-lasting gel polish.', 'Manikura', 'Manicure', 2),
    ('38cba7e8-8117-478d-9b71-caae0f5d4199', 'Manikura + gradavni trajni lak', 'Manicure + builder gel polish', 'Manikura + gradavni trajni lak za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Manicure + builder gel polish for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 3),
    ('eca97b79-eaa0-4f4a-a99e-e225410312e8', 'Muška manikura', 'Men’s manicure', 'Muška manikura za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Men’s manicure for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 10),
    ('9121f0c4-649b-49a9-ac81-724339292e64', 'Nadopuna gela', 'Gel refill', 'Nadopuna gela za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Gel refill for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 5),
    ('c49c81b5-94c0-4731-ae16-8ab772bb42d9', 'Obicna manikura', 'Classic manicure', 'Obicna manikura za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Classic manicure for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 11),
    ('c442352d-00dd-4e27-9da4-0153e78b0dba', 'Popravak nokta', 'Nail repair', 'Popravak nokta za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Nail repair for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 7),
    ('fbd4c79b-1b2d-4f8a-ac45-f011bd2b468b', 'Produživanje Gel', 'Gel nail extension', 'Produživanje Gel za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Gel nail extension for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 6),
    ('4923d906-4baa-41dc-afe1-9d97564ff436', 'Skidanje trajnog laka', 'Gel polish removal', 'Skidanje trajnog laka za uredne, njegovane nokte i ruke uz profesionalnu obradu i završnu njegu.', 'Gel polish removal for neat, well-groomed nails and hands with professional care and a polished finish.', 'Manikura', 'Manicure', 9),
    ('2e9f7cd3-a073-4316-90a2-742bcaa3b3dc', 'Anticelulitna masaža (noge)', 'Anti-cellulite massage (legs)', 'Anticelulitna masaža (noge) pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Anti-cellulite massage (legs) provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 1),
    ('8ba781fb-4910-4d30-8e48-469c68d3cd1d', 'Aroma masaža', 'Aroma massage', 'Aroma masaža pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Aroma massage provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 2),
    ('d417edb1-e5e3-4773-87b3-78e57ea458e1', 'Klasična masaža cijelog tijela', 'Classic full body massage', 'Klasična masaža cijelog tijela pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Classic full body massage provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 3),
    ('3daa7c07-f40e-4416-b2f7-b2f7d2d41ab1', 'Luksuzna masaža s aromatičnim uljima', 'Luxury massage with aromatic oils', 'Luksuzna masaža s aromatičnim uljima pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Luxury massage with aromatic oils provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 4),
    ('7d322b74-78c5-4cd8-a0e8-e06cc1971ccf', 'Masaža stopala', 'Foot massage', 'Masaža stopala pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Foot massage provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 5),
    ('c58f455d-68be-4f7f-b1af-ab33fd02dd7b', 'Parcijalna masaža leđa & vrata', 'Partial back & neck massage', 'Parcijalna masaža leđa & vrata pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Partial back & neck massage provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 6),
    ('f72f90af-1779-42b1-88cd-79850ee68d51', 'Sportska masaža leđa', 'Sports back massage', 'Sportska masaža leđa pruža ciljanu njegu i opuštanje te pomaže smanjiti osjećaj napetosti u tretiranom području.', 'Sports back massage provides targeted care and relaxation, helping to reduce the feeling of tension in the treated area.', 'Masaže', 'Massage', 7),
    ('33ff58c1-e354-478a-a7b6-91261fd7cb4e', 'Brow lift', 'Brow Lift', 'Brow lift za uredno, skladno i prirodno naglašeno područje obrva i trepavica.', 'Brow Lift for a neat, balanced and naturally enhanced brow and lash area.', 'Obrve i trepavice', 'Brows & Lashes', 1),
    ('63e13a17-161d-4b3c-b9da-1e926af32d97', 'Brow lift + bojanje obrva', 'Brow Lift + Tint', 'Oblikovanje, podizanje i bojanje obrva za uredan izgled.', 'Brow lifting and tinting for perfectly shaped and defined brows.', 'Obrve i trepavice', 'Brows & Lashes', 2),
    ('d621eaca-87ab-4b95-b0ba-b6452f44c2a4', 'Oblikovanje i bojanje obrva', 'Brow Shaping & Tint', 'Oblikovanje i bojanje obrva prilagođeno vašem licu.', 'Professional brow shaping and tinting tailored to your facial features.', 'Obrve i trepavice', 'Brows & Lashes', 7),
    ('47f00b63-399a-4d5d-81e6-ba4014c4e552', 'Čupanje obrva', 'Eyebrow tweezing', 'Čupanje obrva za uredno, skladno i prirodno naglašeno područje obrva i trepavica.', 'Eyebrow tweezing for a neat, balanced and naturally enhanced brow and lash area.', 'Obrve i trepavice', 'Brows & Lashes', 3),
    ('02bc5043-f963-41f8-8527-b80bf81dfd55', 'Farbanje obrva', 'Eyebrow tinting', 'Farbanje obrva za uredno, skladno i prirodno naglašeno područje obrva i trepavica.', 'Eyebrow tinting for a neat, balanced and naturally enhanced brow and lash area.', 'Obrve i trepavice', 'Brows & Lashes', 4),
    ('f5e8fda3-eb4a-405b-a0fb-310b45adcee2', 'Lash lift', 'Lash Lift', 'Lash lift za uredno, skladno i prirodno naglašeno područje obrva i trepavica.', 'Lash Lift for a neat, balanced and naturally enhanced brow and lash area.', 'Obrve i trepavice', 'Brows & Lashes', 5),
    ('3d40b00a-0696-44f1-9d10-fc5264bb3a5e', 'Lash lift + brow lift + bojanje – combo', 'Lash Lift + Brow Lift + Tint - Combo', 'Kombinirani tretman za naglašene trepavice i savršeno oblikovane obrve.', 'A complete lash and brow enhancement treatment for a polished natural look.', 'Obrve i trepavice', 'Brows & Lashes', 6),
    ('6c47a056-9822-430b-9ae0-bb1919c1b2c3', 'Lash lift + bojanje trepavica', 'Lash Lift + Tint', 'Podizanje i bojanje trepavica za prirodno izražen pogled.', 'Lash lifting and tinting for naturally fuller-looking lashes.', 'Obrve i trepavice', 'Brows & Lashes', 7),
    ('5a32b32c-7bdf-41a8-aa82-f2f707331ad6', 'Oblikovanje obrva', 'Eyebrow shaping', 'Oblikovanje obrva za uredno, skladno i prirodno naglašeno područje obrva i trepavica.', 'Eyebrow shaping for a neat, balanced and naturally enhanced brow and lash area.', 'Obrve i trepavice', 'Brows & Lashes', 8),
    ('87cc5918-707a-4164-a922-81b15cacc5c5', 'Klasična pedikura', 'Classic Pedicure', 'Njega stopala i noktiju za uredan i njegovan izgled.', 'Professional foot and nail care for healthy, well-groomed feet.', 'Pedikura', 'Pedicure', 1),
    ('c2215361-e737-49d5-815b-48270511f805', 'Kompletna estetska pedikura', 'Full Aesthetic Pedicure', 'Potpuna njega stopala koja uključuje uklanjanje zadebljale kože i njegu noktiju.', 'A complete aesthetic foot care treatment including callus removal and nail care.', 'Pedikura', 'Pedicure', 3),
    ('62e03df3-f395-49d8-a935-29488fafd07b', 'Klasična pedikura + obični lak', 'Classic pedicure + regular polish', 'Klasična pedikura + obični lak za uredna i njegovana stopala i nokte uz profesionalnu obradu i završnu njegu.', 'Classic pedicure + regular polish for neat, well-groomed feet and nails with professional care and a polished finish.', 'Pedikura', 'Pedicure', 2),
    ('eb544dbf-6711-4bde-a906-cdfce6c2ea38', 'Kurije oko / urasli nokti', 'Callus / ingrown nail treatment', 'Kurije oko / urasli nokti za uredna i njegovana stopala i nokte uz profesionalnu obradu i završnu njegu.', 'Callus / ingrown nail treatment for neat, well-groomed feet and nails with professional care and a polished finish.', 'Pedikura', 'Pedicure', 6),
    ('ff649b14-c5e7-4fc9-9cfe-f520bc9dde64', 'Muška pedikura', 'Men’s pedicure', 'Muška pedikura za uredna i njegovana stopala i nokte uz profesionalnu obradu i završnu njegu.', 'Men’s pedicure for neat, well-groomed feet and nails with professional care and a polished finish.', 'Pedikura', 'Pedicure', 5),
    ('bd7e0a81-c5ae-4007-a702-7b85dc5b6638', 'Pedikura + trajni lak', 'Pedicure + Gel Polish', 'Pedikura uz dugotrajni gel lak za savršena stopala.', 'Professional pedicure finished with long-lasting gel polish.', 'Pedikura', 'Pedicure', 4),
    ('d5fbc450-c9ef-43d7-85e1-fd18d23d1bfa', 'Pedikura + trajni lak', 'Pedicure + gel polish', 'Pedikura + trajni lak za uredna i njegovana stopala i nokte uz profesionalnu obradu i završnu njegu.', 'Pedicure + gel polish for neat, well-groomed feet and nails with professional care and a polished finish.', 'Pedikura', 'Pedicure', 4),
    ('6a10d57e-4769-49a0-a79b-387a20761969', 'Popravak Nokta', 'Nail Repair', 'Popravak Nokta za uredna i njegovana stopala i nokte uz profesionalnu obradu i završnu njegu.', 'Nail Repair for neat, well-groomed feet and nails with professional care and a polished finish.', 'Pedikura', 'Pedicure', 7),
    ('b87f5da8-dd17-4d0a-9c39-942b619fe14e', 'Spray Ten', 'Spray Tan', 'Spray Ten za ujednačen, prirodan preplanuli izgled bez izlaganja UV zračenju.', 'Spray Tan for an even, natural-looking tan without UV exposure.', 'Spray Tan', 'Spray Tan', 1),
    ('40e4d35a-7f40-4929-9c8a-a06e9044780e', 'Spray Ten + Piling cijelog tijela', 'Spray Tan + Full Body Exfoliation', 'Spray Ten + Piling cijelog tijela za ujednačen, prirodan preplanuli izgled bez izlaganja UV zračenju.', 'Spray Tan + Full Body Exfoliation for an even, natural-looking tan without UV exposure.', 'Spray Tan', 'Spray Tan', 2),
    ('697c5f0a-fb0a-4879-bc87-3ef9d336d953', 'Aparatna limfna drenaža', 'Mechanical Lymphatic Drainage', 'Nježan tretman koji potiče limfnu cirkulaciju, smanjuje zadržavanje tekućine i osjećaj težine u nogama.', 'A gentle treatment that stimulates lymphatic circulation, reduces fluid retention and relieves heavy legs.', 'Njega tijela', 'Body Treatments', 1),
    ('69334009-9622-4fb1-adbd-d36b083d1366', 'HIFU tijelo - Zatezanje kože', 'HIFU body – skin tightening', 'HIFU tijelo - Zatezanje kože je profesionalni tretman tijela usmjeren na njegu, oblikovanje i osjećaj lakoće.', 'HIFU body – skin tightening is a professional body treatment focused on care, contouring and a lighter, refreshed feeling.', 'Njega tijela', 'Body Treatments', 2),
    ('3c22970f-8ebc-4e54-9857-c46809167340', 'LAKOĆA – Drenažni program', 'LIGHTNESS – drainage program', 'LAKOĆA – Drenažni program je profesionalni tretman tijela usmjeren na njegu, oblikovanje i osjećaj lakoće.', 'LIGHTNESS – drainage program is a professional body treatment focused on care, contouring and a lighter, refreshed feeling.', 'Njega tijela', 'Body Treatments', 3),
    ('6e0d6c04-aa27-47f6-bfb0-95bd207ff616', 'LIPOSONIX - Smanjenje masnih naslaga', 'LIPOSONIX – fat reduction', 'LIPOSONIX - Smanjenje masnih naslaga je profesionalni tretman tijela usmjeren na njegu, oblikovanje i osjećaj lakoće.', 'LIPOSONIX – fat reduction is a professional body treatment focused on care, contouring and a lighter, refreshed feeling.', 'Njega tijela', 'Body Treatments', 4),
    ('f0c63a62-6126-4d80-9615-54760f34422c', 'OBLIK – Anticelulit i oblikovanje', 'SHAPE – anti-cellulite and body shaping', 'OBLIK – Anticelulit i oblikovanje je profesionalni tretman tijela usmjeren na njegu, oblikovanje i osjećaj lakoće.', 'SHAPE – anti-cellulite and body shaping is a professional body treatment focused on care, contouring and a lighter, refreshed feeling.', 'Njega tijela', 'Body Treatments', 5),
    ('aa5380d4-c5d8-47d1-ba8f-c2a13b0b8880', 'PRESTIGE TRANSFORMATION – Intenzivniji program oblikovanja tijela', 'PRESTIGE TRANSFORMATION – intensive body shaping program', 'PRESTIGE TRANSFORMATION – Intenzivniji program oblikovanja tijela je profesionalni tretman tijela usmjeren na njegu, oblikovanje i osjećaj lakoće.', 'PRESTIGE TRANSFORMATION – intensive body shaping program is a professional body treatment focused on care, contouring and a lighter, refreshed feeling.', 'Njega tijela', 'Body Treatments', 6),
    ('059c8015-46f4-4a67-8866-4b567dbaa6e5', 'Summer Detox paket', 'Summer Detox Pack', 'Kompletan program za oblikovanje tijela, detoksikaciju i osjećaj lakoće.', 'A complete body contouring and detox program designed to leave you feeling lighter and refreshed.', 'Njega tijela', 'Body Treatments', 7),
    ('a5c7997e-a177-41ce-8d57-50749c5f11a1', 'Vela Shape + Kavitacija', 'VelaShape + Cavitation', 'Kombinacija tretmana za oblikovanje tijela, smanjenje celulita i lokaliziranih masnih naslaga.', 'A body contouring treatment combining cellulite reduction and targeted fat reduction.', 'Njega tijela', 'Body Treatments', 8)
)
update public.services s
set
  name = u.name,
  name_en = u.name_en,
  description = u.description,
  description_en = u.description_en,
  service_group = u.service_group,
  service_group_en = u.service_group_en,
  display_order = u.display_order
from service_updates u
where s.id = u.id::uuid;

update public.services
set
  price_cents = null,
  price_min_cents = 5000,
  price_max_cents = 6500
where id = '4b5bc4a4-b6d5-4b1c-98e6-7495d12e2066'::uuid;

create index if not exists services_group_display_order_idx
  on public.services(service_group, display_order, name);

commit;
